# Example docker-compose file for setting up server.
# Directus as Headless CMS
# Nuxt.js
# Swag as Webserver and automantes SSL server from Let's Encrypt
version: '3.2'
services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
    environment:
      KEY: 'replace-with-random-value'
      SECRET: 'replace-with-random-value'
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'password'
      DB_CLIENT: 'sqlite3'
      DB_FILENAME: '/directus/database/data.db'
      WEBSOCKETS_ENABLED: 'true'
      CORS_ENABLED: 'true'
      CORS_ORIGIN: 'true'
      ACCESS_TOKEN_TTL: '1d'
      REFRESH_TOKEN_COOKIE_NAME: 'sudb_refresh_token'
    restart: always

  # swag:
  #   image: ghcr.io/linuxserver/swag:version-1.14.0
  #   container_name: swag
  #   cap_add:
  #     - NET_ADMIN
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Asia/India
  #     - URL=50.16.95.162
  #     - SUBDOMAINS=www,api #wildcard
  #     - VALIDATION=http
  #   networks:
  #     - directus
  #   volumes:
  #     - ./config:/config
  #   ports:
  #     - 443:443
  #     - 80:80
  #   restart: always

  node:
    image: node:18-alpine
    container_name: nuxt_app
    volumes:
      - ./nuxt:/usr/src/app/
    working_dir: /usr/src/app
    environment:
      HOST: '0.0.0.0'
    networks:
      - directus
    restart: always
    env_file:
      - ./nuxt/.env
    ports:
      - 80:3000
    # for production
    # command: [sh, -c, "yarn add nuxt && yarn build && set NODE_ENV=production && yarn start"]
    command: [ sh, -c, "npm i nuxt && npm run build && npm run start" ]
    # for development
    # command: [ sh, -c, "npm i nuxt && npm run dev" ]

networks:
  directus:
